server:
  port: 80

spring:
  application:
    name: cloud-zookeeper-consumer-order80
  cloud:
    zookeeper:
      connect-string: 192.168.2.100:2181  # zk地址

payment:
  server:
    url: http://cloud-zookeeper-provider-payment8004