server:
  port: 7001
eureka:
  instance:
    # hostname: localhost #eureka服务端的实例名称
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否将本服务注册到eureka中
    fetch-registry: false #是否从eureka中获取注册服务
    service-url:
      # #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #单节点版
      defaultZone: http://eureka7002.com:7002/eureka #集群版
  server:
    # 使用7001单节点"关闭自我保护"测试，如果是集群模式，集群版需要配置。这里对应测试的服务是8001,8001上也需要做对应的配置
    #关闭自我保护机制，保证不可用服务被及时踢除 (使用7001单节点测试)
    #enable-self-preservation: false
    #默认是10分钟，这里设置2秒 (使用7001单节点测试)
    #eviction-interval-timer-in-ms: 2000
