# 单机模式 provider
server:
  port: 8005

spring:
  application:
    name: cloud-provider-payment8005

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7003/eureka/

  instance:
    instance-id: payment8005  # 实例名称
    prefer-ip-address: true # 访问路径可以显示ip

