server:
  port: 80

spring:
  application:
    name: cloud-feign-hystrix-consumer-order80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7003/eureka/

logging:
  level:
    org.fwx.service.*: debug #

feign:
  client:
    config:
      default:  # 默认配置
        connect-timeout: 10000
        read-timeout: 10000
  hystrix:  # 开启feign的hystrix支持
    enabled: true

# 这里的超时必须和上面一起使用才生效
# ！！！feign:client:config:default:connect-timeout: 10000
#                                   read-timeout: 10000
# 配置feign的hystrix超时时间，默认是1s，这里设置10s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

