server:
  port: 8401

# 配置Spring Boot应用的基本信息
spring:
  application:
    name: cloudalibaba-sentinel-service8401 # 应用名称
  # 配置云服务发现
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务注册中心地址
    # 配置Sentinel相关信息
    sentinel:
      transport:
        dashboard: localhost:8080 # 配置Sentinel控制台地址
        port: 8719 # 客户端与Sentinel控制台通信的端口
      # 配置数据源，这里配置了名为ds1的Sentinel数据源
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848 # 指定Nacos服务注册中心地址
            dataId: cloudalibaba-sentinel-service # 指定在Nacos中配置的资源规则的数据ID
            groupId: DEFAULT_GROUP # 指定在Nacos中配置的资源规则的分组ID
            data-type: json # 指定数据类型为JSON
            rule-type: flow # 指定规则类型为流控规则


management:
  endpoints:
    web:
      exposure:
        include: '*'

#feign:
#  sentinel:
#    enabled: true # 激活Sentinel对Feign的支持


